name: Alex Halperin
favicon: null
layout_spectrum: 0.6647758921608329
typography_spectrum: 0.811980084516108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9288328653201461
  lightness: 0.8073927655350417
  saturation: 0.4666890862863511
  rhythmicContrast: 0.3688602913171053
purpose: []
